[build]
publish = "dist"
command = "perl -0777 -i -pe 's/<!--.*?-->//gs' slides.md && npm run build -- --base /django-life/"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
